adding the user management part
l-eduardo/potential-pancake pull request #8
Opened 2023-11-14 23:38 UTC by Abmaelbt

2023-11-16 03:30 UTC, hsato03 approved these changes
O registro e login de usuários tá funcionando legal, só precisaria arrumar aquela parte do redirecionamento e talvez remover a nova entidade `Order` e as classes que usam ela.

2023-11-16 03:30 UTC, hsato03 commented on user/views.py
> +from .filters import OrderFilter
```suggestion
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages

from .forms import CreateUserForm
```

2023-11-16 03:30 UTC, hsato03 commented on user/views.py
> +            return redirect('tasks')
```suggestion
            return redirect('tasks:list_tasks')
```
Conserta o redirecionamento com o merge do [PR#9](https://github.com/l-eduardo/potential-pancake/pull/9).

2023-11-16 04:54 UTC, l-eduardo requested changes
Creio que a classe Order não tenha utilidade, podemos remover?

2023-11-16 04:54 UTC, l-eduardo commented on user/models.py
> +        return self.order_numer
Esse classe e seus derivados filters, views e etc. Podem ser removidos, pois pelo que parece não estão sendo usados. Correto?

```suggestion

```

2023-11-16 04:54 UTC, l-eduardo commented on user/filters.py
> +    pass
```suggestion
```

2023-11-16 04:54 UTC, l-eduardo commented on user/forms.py
> +        fields = '__all__'
```suggestion
```

2023-11-16 09:53 UTC, Abmaelbt reviewed
De fato, não tava sendo usado. É que eu tava testando melhor como funcionava a questão dos models e como deveria ser se o modelo de formulário para cadastrar os usuários ficasse la dentro.

A parte do filters era pra fazer a classificação de quais usuários acessariam determinada parte do sistema, mas acredito que não vamos implementar isso então por enquanto deixa assim.

2023-11-17 16:45 UTC, l-eduardo approved these changes

2023-11-17 16:45 UTC, merged